name: Miniutility
version: '1.21.8'
main: org.hotamachisubaru.miniutility.MiniutilityLoader
bootstrapper: org.hotamachisubaru.miniutility.PluginLoad.MiniutilityBootstrap
api-version: "1.19"
authors:
  - hotamachisubaru
folia-supported: true
plugin-dependencies:
  - name: LuckPerms
    required: false
    bootstrap: false
# ここからコマンド定義を追加
commands:
  menu:
    description: 便利機能を開きます。
    usage: /<command>
  load:
    description: データベースからニックネームをロードします。
    usage: /<command>
  prefixtoggle:
    description: Prefix表示を切り替えます。
    usage: /<command>
