name: Miniutility
version: '1.21.1'
main: org.hotamachisubaru.miniutility.Miniutility
api-version: '1.21'
author: hotamachisubaru
description: copyright 2024 hotamachisubaru all rights reserved.
commands:
  menu:
    description: 便利ツールを集めました。
    usage: /menu
