name: Miniutility
version: '${project.version}'
main: org.hotamachisubaru.miniutility.Miniutility
api-version: '1.21'
author: hotamachisubaru
load: STARTUP
folia-supported: true
softdepend:
  - LuckPerms
description: copyright 2024-2025 hotamachisubaru all rights reserved.
commands:
  menu:
    description: 便利ツールを集めました。
    usage: /menu
  load:
    description: データベースからニックネームをロードします。
    usage: /load
    permission: miniutility.load
  prefixtoggle: # /prefixtoggle で ON/OFF 切り替え
      description: Prefix とニックネームの結合を ON/OFF 切り替えします
      usage: /prefixtoggle
      permission: miniutility.toggleprefix
permissions:
  load:
    description: データベースからニックネームをロードします。
    default: op

