name: Miniutility
version: '${project.version}'
main: org.hotamachisubaru.miniutility.Miniutility
api-version: '1.21'
author: hotamachisubaru
load: STARTUP
softdepend:
  - LuckPerms
description: copyright 2024-2025 hotamachisubaru all rights reserved.
commands:
  menu:
    description: 便利ツールを集めました。
    usage: /menu
  load:
    description: データベースからニックネームをロードします。
    usage: /load
    permission: miniutility.load
permissions:
  load:
    description: データベースからニックネームをロードします。
    default: op

