name: Miniutility
version: '1.21.8'
main: org.hotamachisubaru.miniutility.MiniutilityLoader
api-version: '1.17'
author: hotamachisubaru
load: STARTUP
description: copyright 2024-2025 hotamachisubaru all rights reserved.
commands:
  menu:
    description: 便利機能を開きます。
    usage: /<command>
  load:
    description: データベースからニックネームをロードします。
    usage: /<command>
    permission: op
  prefixtoggle:
    description: prefixの結合を変更します
    usage: /<command>
permissions:
  load:
    description: データベースからニックネームをロードします。
    default: op
