name: Miniutility
version: '1.21.8'
main: org.hotamachisubaru.miniutility.MiniutilityLoader
api-version: '1.21'
author: hotamachisubaru
load: STARTUP
description: copyright 2024-2025 hotamachisubaru all rights reserved.
permissions:
  load:
    description: データベースからニックネームをロードします。
    default: op
